import java.util.*;
public class Demo {
  public static void initDemo(){
      ArrayList<String> locationListDemo = new ArrayList<String>();
      ArrayList<String> piecesListDemo = new ArrayList<String>();
      ArrayList<String> colorListDemo = new ArrayList<String>();
      ArrayList<String> solutionDemo= new ArrayList<String>();

      solution.add("h2 h4");
      solution.add("a8 b8");
      solution.add("h4 h5");
      solution.add("g7 g5");
      solution.add("h5 g6");

      locationList.add("66");
      colorList.add("black");
      piecesList.add("pawn");
      locationList.add("71");
      colorList.add("white");
      piecesList.add("pawn");
      locationList.add("07");
      colorList.add("black");
      piecesList.add("king");
      locationList.add("00");
      colorList.add("white");
      piecesList.add("king");
      ChessPuzzle.solve("enpassant, which is when a pawn can capture an opponent pawn if that pawn has moved immediately two squares and is directly adjacent to your pawn",locationList,piecesList,colorList,solution,"white",true);
      solution.clear();
      colorList.clear();
      piecesList.clear();
      locationList.clear();

      solution.add("h3 h4");
      locationList.add("71");
      colorList.add("white");
      piecesList.add("pawn");
      locationList.add("54");
      colorList.add("black");
      piecesList.add("king");
      locationList.add("00");
      colorList.add("white");
      piecesList.add("king");
      ChessPuzzle.solve("invalid move due to invalid start square",locationList,piecesList,colorList,solution,"white",true);
      solution.clear();
      colorList.clear();
      piecesList.clear();
      locationList.clear();

      solution.add("h2 h5");
      locationList.add("71");
      colorList.add("white");
      piecesList.add("pawn");
      locationList.add("54");
      colorList.add("black");
      piecesList.add("king");
      locationList.add("00");
      colorList.add("white");
      piecesList.add("king");
      ChessPuzzle.solve("invalid move due to invalid destination square",locationList,piecesList,colorList,solution,"white",true);
      solution.clear();
      colorList.clear();
      piecesList.clear();
      locationList.clear();

      solution.add("h3 h4");
      locationList.add("71");
      colorList.add("white");
      piecesList.add("pawn");
      locationList.add("54");
      colorList.add("black");
      piecesList.add("king");
      locationList.add("00");
      colorList.add("white");
      piecesList.add("king");
      ChessPuzzle.solve("invalid move due to invalid start and destination square",locationList,piecesList,colorList,solution,"white",true);
      solution.clear();
      colorList.clear();
      piecesList.clear();
      locationList.clear();

      solution.add("h7 h8 N");
      locationList.add("76");
      colorList.add("white");
      piecesList.add("pawn");
      locationList.add("54");
      colorList.add("black");
      piecesList.add("king");
      locationList.add("00");
      colorList.add("white");
      piecesList.add("king");
      ChessPuzzle.solve("promote with specificed piece",locationList,piecesList,colorList,solution,"white",true);
      solution.clear();
      colorList.clear();
      piecesList.clear();
      locationList.clear();

      solutionDemo.add("f5 f7");
      locationListDemo.add("54");
      colorListDemo.add("white");
      piecesListDemo.add("queen");
      locationListDemo.add("77");
      colorListDemo.add("black");
      piecesListDemo.add("king");
      locationListDemo.add("00");
      colorListDemo.add("white");
      piecesListDemo.add("king");
      ChessPuzzle.solve("stalemate",locationListDemo,piecesListDemo,colorListDemo,solutionDemo,"white",true);
      solutionDemo.clear();
      colorListDemo.clear();
      piecesListDemo.clear();
      locationListDemo.clear();

      solutionDemo.add("h7 h8");
      locationListDemo.add("76");
      colorListDemo.add("white");
      piecesListDemo.add("pawn");
      locationListDemo.add("54");
      colorListDemo.add("black");
      piecesListDemo.add("king");
      locationListDemo.add("00");
      colorListDemo.add("white");
      piecesListDemo.add("king");
      ChessPuzzle.solve("default promote",locationListDemo,piecesListDemo,colorListDemo,solutionDemo,"white",true);
      solutionDemo.clear();
      colorListDemo.clear();
      piecesListDemo.clear();
      locationListDemo.clear();

      solutionDemo.add("e1 g1");
      locationListDemo.add("40");
      colorListDemo.add("white");
      piecesListDemo.add("king");
      locationListDemo.add("13");
      colorListDemo.add("black");
      piecesListDemo.add("bishop");
      locationListDemo.add("01");
      colorListDemo.add("white");
      piecesListDemo.add("pawn");
      locationListDemo.add("70");
      colorListDemo.add("white");
      piecesListDemo.add("rook");
      locationListDemo.add("16");
      colorListDemo.add("black");
      piecesListDemo.add("king");

      ChessPuzzle.solve("castle through check, which is not legal",locationListDemo,piecesListDemo,colorListDemo,solutionDemo,"white",true);
      solutionDemo.clear();
      colorListDemo.clear();
      piecesListDemo.clear();
      locationListDemo.clear();
 }
}
